services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  auth_postgres:
    image: postgres:16
    container_name: auth_postgres
    environment:
      POSTGRES_USER: auth_db
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    ports:
      - "5132:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  auth_postgres_data: