services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"    # AMQP
      - "15673:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  auth_postgres:
    image: postgres:16
    container_name: auth_postgres
    environment:
      POSTGRES_USER: auth_db
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    ports:
      - "5132:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  
  matchmaking_postgres:
    image: postgres:16
    container_name: matchmaking_postgres
    environment:
      POSTGRES_USER: match_db
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: match_db
    ports:
      - "5133:5432"
    volumes:
      - match_making_postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    
  gameservice_postgres:
    image: postgres:16
    container_name: gameservice_postgres
    environment:
      POSTGRES_USER: gameservice_db
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gameservice_db
    ports:
      - "5134:5432"
    volumes:
      - gameservice_postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  auth_postgres_data:
  match_making_postgres_data:
  gameservice_postgres_data: